
  get:      
    description: ID of employee
    responses: 
      200:
        description: Transfer done  
        body: 
          application/json:
            example : {
              status : "SUCCESS",
              data : {  
                  name : "Zaw Than Oo",
                  email : "zawthanoo@gmail.com",
                  phone : "+959420000777",
                  dob : "1986-12-02"
              }
            }